INSERT INTO employee(name, last_name, email, phone, position, active) values ('Brandon','Sanderson','bs@test.com','192748192','Cook',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Christopher','Paolini','cp@test.com','274927251','Fireman',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Jack','Campbell','jc@test.com','204738291','Writer',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Peter','Brett','pb@test.com','768948562','Policeman',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Robert','Wegner','rw@test.com','917202634','Lawyer',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('John','Moore','jm@test.com','192037462','Pimp',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Terry','Pratchett','tp@test.com','182940281','Postman',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Henry','Lion Oldi','hlo@test.com','192038462','Stuntman',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Ursula','LeGuin','ul@test.com','875409123','Queen',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Robert','Martin','rm@test.com','987283710','UncleBob',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Cay','Horstman','ch@test.com','109287265','Programmer',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Stephen','Prata','sp@test.com','433849098','Programmer',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Dan','Brown','db@test.com','738277192','Legend',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Gene','Wolfe','gw@test.com','271937102','Carpenter',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Chris','Jordan','cj@test.com','820174927','Doctor',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Fredrick','Forsyth','ff@test.com','918204761','Surgeon',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Tom','Clancy','tc@test.com','192037261','Pilot',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Ken','Follett','kf@test.com','019283746','Nurse',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Robert','Ludlum','rl@test.com','982736102','Killer',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Clive','Cussler','cc@test.com','982637199','Painter',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('John','Tolkien','jt@test.com','928371029','King',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Dominic','Barker','db@test.com','98762871','Robber',true);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Aleksander','Rudazow','ar@test.com','981720164','Bartender',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Trudi','Canavan','tc@test.com','987654213','Cashier',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Karen','Miller','km@test.com','753619281','Chimney Sweep',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Joe','Abercrombie','ja@test.com','524152418','Editor',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Craig','Walls','cw@test.com','098712345','Youtuber',false);
INSERT INTO employee(name, last_name, email, phone, position, active) values ('Alex','Garcia','ag@test.com','528102946','Tester',false);